import pandas as pd

# to see items in a columns.

In [3]:
df['Installs'].value_counts()

1,000,000+        1579
10,000,000+       1252
100,000+          1169
10,000+           1054
1,000+             907
5,000,000+         752
100+               719
500,000+           539
50,000+            479
5,000+             477
100,000,000+       409
10+                386
500+               330
50,000,000+        289
50+                205
5+                  82
500,000,000+        72
1+                  67
1,000,000,000+      58
0+                  14
Free                 1
0                    1
Name: Installs, dtype: int64

# To search for some specific row and drop it
# Drop rows


In [5]:
i = df[df.Installs == 'Free'].index
i

Int64Index([10472], dtype='int64')

In [6]:
df=df.drop(i)

In [7]:
df.Installs.value_counts()

1,000,000+        1579
10,000,000+       1252
100,000+          1169
10,000+           1054
1,000+             907
5,000,000+         752
100+               719
500,000+           539
50,000+            479
5,000+             477
100,000,000+       409
10+                386
500+               330
50,000,000+        289
50+                205
5+                  82
500,000,000+        72
1+                  67
1,000,000,000+      58
0+                  14
0                    1
Name: Installs, dtype: int64

In [8]:
i = df[df.Installs == '1+'].index
i

Int64Index([  649,   652,  2422,  2425,  2454,  2462,  2471,  4218,  4459,
             4471,  4550,  5126,  5160,  5171,  5500,  5812,  5832,  5837,
             5846,  5857,  5917,  5921,  6239,  6257,  6277,  6479,  6624,
             6888,  6962,  7225,  7231,  7370,  7521,  7522,  7737,  8019,
             8150,  8242,  8355,  8489,  8509,  8612,  8729,  8870,  8876,
             9101,  9104,  9139,  9201,  9262,  9264,  9302,  9453,  9532,
             9664, 10101, 10299, 10417, 10530, 10541, 10654, 10697, 10701,
            10708, 10745, 10764, 10775],
           dtype='int64')

In [ ]:
#  searching a column by multiple filter and then deleting it
i = df[((df.Name == 'jhon') &( df.Age == 15) & (df.Grade == 'A'))].index
df=df.drop(i)

# To replace a specific part of a string in a column

In [9]:
df.Installs=df.Installs.str.replace('+','')

In [10]:
df

App             Category  \
0         Photo Editor & Candy Camera & Grid & ScrapBook       ART_AND_DESIGN   
1                                    Coloring book moana       ART_AND_DESIGN   
2      U Launcher Lite – FREE Live Cool Themes, Hide ...       ART_AND_DESIGN   
3                                  Sketch - Draw & Paint       ART_AND_DESIGN   
4                  Pixel Draw - Number Art Coloring Book       ART_AND_DESIGN   
...                                                  ...                  ...   
10836                                   Sya9a Maroc - FR               FAMILY   
10837                   Fr. Mike Schmitz Audio Teachings               FAMILY   
10838                             Parkinson Exercices FR              MEDICAL   
10839                      The SCP Foundation DB fr nn5n  BOOKS_AND_REFERENCE   
10840      iHoroscope - 2018 Daily Horoscope & Astrology            LIFESTYLE   

       Rating Reviews                Size    Installs  Type Price  \
0         4.1     159                 19M      10,000  Free     0   
1         3.9     967                 14M     500,000  Free     0   
2         4.7   87510                8.7M   5,000,000  Free     0   
3         4.5  215644                 25M  50,000,000  Free     0   
4         4.3     967                2.8M     100,000  Free     0   
...       ...     ...                 ...         ...   ...   ...   
10836     4.5      38                 53M       5,000  Free     0   
10837     5.0       4                3.6M         100  Free     0   
10838     NaN       3                9.5M       1,000  Free     0   
10839     4.5     114  Varies with device       1,000  Free     0   
10840     4.5  398307                 19M  10,000,000  Free     0   

      Content Rating                     Genres      Last Updated  \
0           Everyone               Art & Design   January 7, 2018   
1           Everyone  Art & Design;Pretend Play  January 15, 2018   
2           Everyone               Art & Design    August 1, 2018   
3               Teen               Art & Design      June 8, 2018   
4           Everyone    Art & Design;Creativity     June 20, 2018   
...              ...                        ...               ...   
10836       Everyone                  Education     July 25, 2017   
10837       Everyone                  Education      July 6, 2018   
10838       Everyone                    Medical  January 20, 2017   
10839     Mature 17+          Books & Reference  January 19, 2015   
10840       Everyone                  Lifestyle     July 25, 2018   

              Current Ver         Android Ver  
0                   1.0.0        4.0.3 and up  
1                   2.0.0        4.0.3 and up  
2                   1.2.4        4.0.3 and up  
3      Varies with device          4.2 and up  
4                     1.1          4.4 and up  
...                   ...                 ...  
10836                1.48          4.1 and up  
10837                 1.0          4.1 and up  
10838                 1.0          2.2 and up  
10839  Varies with device  Varies with device  
10840  Varies with device  Varies with device  

[10840 rows x 13 columns]

# To convert a string columns to numeric and converting all error terms to null

In [ ]:
df['09-12-2013']= pd.to_numeric(df['09-12-2013'],errors='coerce')
df['09-12-2013'].dtype

# To change the value or replace multiple variable in a column

In [ ]:
df1.Style=df1.Style.apply(lambda x: 'Sexy' if x=='sexy' else x)
df1.Style.value_counts()

# To replace variable in a columns

In [ ]:
df1.NeckLine=df1.NeckLine.replace('sweetheart','Sweetheart')
df1.NeckLine.value_counts()

# To replace multiple variable to one in a column

In [ ]:
wholesale.Channel=wholesale.Channel.replace(['R','Rest'],'Restaurant')

# Use fuzzywuzzy to replace multiple variable to one

In [ ]:
!pip install fuzzywuzzy
from fuzzywuzzy import fuzz
fuzz.ratio("Catherine M. Gitau","Catherine Gitau")
df1.SleeveLength = df1.SleeveLength.apply(lambda x: 'sleeveless' if fuzz.ratio(x,'sleeveless') >= 90 else x)
df1.SleeveLength.value_counts()

# if it throws error that ur string columns have float

In [ ]:
# u can check what is it due to
df1[df1.Material.apply(lambda x: isinstance(x,float)==True)]

# Drop columns

In [ ]:
df1 = df1.drop(['FabricType', 'Decoration'], axis=1)

# To take help in notebook 

In [11]:
help(r2_score)

NameError: name 'r2_score' is not defined

# To rename columns

In [ ]:
res=res.rename(columns={'Views_show':'lag_variable'})

# Merging

In [ ]:
df=pd.merge(churn,internet,on='customerID',how='inner')
df.head()

# Concat

In [ ]:
df1=pd.concat([df1,df2],axis=1)
df1.head()

# Count values for all the columns in the data frame

In [ ]:
for i in df1.columns:
    print(df1[i].value_counts())

# For added describe functions percentile

In [ ]:
df1.describe(percentiles=[0.25,0.90,0.99])

# To ignore warnings

In [ ]:
import warnings
warnings.filterwarnings('ignore')

# To see all row and columns if many rows and columns are there

In [ ]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

# To rename column

In [ ]:
y_test_pred=y_test_final.rename(columns={0:'churn_prob'})

# TO rearrange columns 

In [ ]:
y_test_pred=y_test_pred.reindex_axis(['cust_id','Churn','churn_prob'],axis=1)
y_test_pred.head()

# To remove a column keep it in a data frame and keep rest columns in other data frame 

In [ ]:
y_train=train_df.pop('price')
X_train=train_df

# To sort values in ascending order

In [ ]:
df.sort_values(by='VIF',ascending=False)

# To round off values

In [ ]:
vif['VIF']=vif['VIF'].round(2)

# To capitalize all the first letter of all words

In [ ]:
input_string.title()

# To capitalize only first letter of first word

In [ ]:
x = txt.capitalize()

# To groupby columns and aggregate

In [ ]:
df=wholesale.groupby('Channel')['Fresh','Milk','Grocery','Frozen','Detergents_Paper','Delicassen'].agg(['sum','count'])

# To groupby specific columns and aggregate

In [ ]:
df=df.groupby('group').agg({'a':['sum', 'max'], 
                         'b':'mean', 
                         'c':'sum', 
                         'd': lambda x: x.max() - x.min()})

# If file is not read u can use encoding to sort error

In [ ]:
df=pd.read_csv(r'C:\Users\user\Downloads\Online+Retail (1).csv',encoding='latin1')

# Checking the % of missing values in the data

In [ ]:
round(100*(df.isnull().sum()/len(df)),2)

# To drop all rows with null values

In [ ]:
df=df.dropna()

# value_counts of all columns:

In [1]:
for i in df.columns:
    print(df[i].value_counts())

NameError: name 'df' is not defined

# to set index to 0,1,--

In [ ]:
monetary=monetary.reset_index()

# To convert any data type to datetime object

In [ ]:
df['InvoiceDate']=pd.to_datetime(df['InvoiceDate'],format='%d-%m-%Y %H:%M')
# fomat will change according to the object format type

# To convert data type of a column

In [ ]:
df = df.astype(int)

# To extract days from a datetime object

In [ ]:
import datetime as dt
df1['recency']=df1['recency'].dt.days
df1.head()


# statistical outliers removal

In [ ]:
q1=df1['Monetary'].quantile(0.05)
q2=df1['Monetary'].quantile(0.95)
iqr=q2-q1
df1=df1[(df1['Monetary']>=q1-(1.5*iqr)) & (df1['Monetary']<=q2+(1.5*iqr))]

# to change x ticks of a plot

In [ ]:
plt.plot(ssn) 
plt.xticks(ticks=[0,1,2,3,4,5,6],labels=[2,3,4,5,6,7,8])
plt.show()

# To make a boxplot

In [ ]:
plt.boxplot(df1.Frequency)

# 2 axis box plot

In [ ]:
sns.boxplot(x='cust_label',y='Frequency',data=df1)

# To reshape 

In [ ]:
cut_tree(merging,n_clusters=3).reshape(-1,)
# -1 represent let that part be same 

# To convert continuous variable to categories variable

In [ ]:
bank['age_bins']=pd.cut(bank['age'],[0,20,30,40,50,60,70,80,90,100],labels=['0-20','20-30','30-40','40-50','50-60','60-70','70-80','80-90','90-100'])

# To plot value count 

In [ ]:
job_df=pd.DataFrame(bank['job'].value_counts().sort_values(ascending=True))
job_df.head()
sns.barplot(job_df.index,job_df['job'])

#  dictionary

In [13]:
dictionary={}
dictionary['spain']='madrid'
dictionary

{'spain': 'madrid'}

In [14]:
dictionary.keys()

dict_keys(['spain'])

In [15]:
dictionary.values()

dict_values(['madrid'])

In [16]:
dictionary['india']='delhi'

In [17]:
dictionary

{'spain': 'madrid', 'india': 'delhi'}

In [18]:
dictionary.items()

dict_items([('spain', 'madrid'), ('india', 'delhi')])

In [19]:
del dictionary['spain']
dictionary

{'india': 'delhi'}

In [20]:
dictionary.clear()

In [21]:
dictionary

{}

# * args and **kwargs

In [22]:
# .items() is used to break dictionary into parts and use the components-----------------------------------------------
def f(*args):
    for i in args:
        print(i)
f(1)
print("")
f(1,2,3,4)
# flexible arguments **kwargs that is dictionary
def f(**kwargs):
    """ print key and value of dictionary"""
    for key, value in kwargs.items():               # If you do not understand this part turn for loop part and look at dictionary in for loop
        print(key, " ", value)
f(country = 'spain', capital = 'madrid', population = 123456)

1

1
2
3
4
country   spain
capital   madrid
population   123456


# Iterator

In [23]:
name = "ronaldo"
it = iter(name)
print(next(it))    # print next iteration
print(*it)   # print all iterator value

r
o n a l d o


# Zip  and unzip two lists


In [24]:
# you can zip any no of lists
a=[1,3,5,7,9]
b=[2,4,6,8]
z=zip(a,b)
z_list=list(z)
for i, j in z_list:
    print(i,j)
z_unzip=list(zip(*z_list))
print(z_unzip)

1 2
3 4
5 6
7 8
[(1, 3, 5, 7), (2, 4, 6, 8)]


# conditionals on iterables

In [25]:
# Conditionals on iterable
num1 = [5,10,15]
num2 = [i**2 if i == 10 else i-5 if i < 7 else i+5 for i in num1]
print(num2)

[0, 100, 20]


# To melt dataframe

In [ ]:
# lets melt
# id_vars = what we do not wish to melt
# value_vars = what we want to melt
melted = pd.melt(frame=data_new,id_vars = 'Name', value_vars= ['Attack','Defense'])
melted

# To drop nan values without using new object

In [ ]:
data1["Type 2"].dropna(inplace = True)  # inplace = True means we do not assign it to new variable. Changes automatically assigned to data
# So does it work ?

# To give NaN value an element

In [ ]:
df.loc[3,'Visitors']=np.nan

# To check statements

In [ ]:
assert  data['Type 2'].notnull().all() # returns nothing because we do not have nan values
# if not true will throw an error

# To make data frame from dictionary

In [28]:
import pandas as pd
country = ["Spain","France"]
population = ["11","12"]
list_label = ["country","population"]
list_col = [country,population]
zipped = list(zip(list_label,list_col))
data_dict = dict(zipped)
df = pd.DataFrame(data_dict)
df


country population
0   Spain         11
1  France         12

# Broadcasting

In [29]:
df["income"] = 0 #Broadcasting entire column
df

country population  income
0   Spain         11       0
1  France         12       0

# If u have set new index them u can directly excess the whole row using the index value

In [ ]:
data2= data2.set_index("date")
df.loc['3/1/2017']
# before if we have to get all the column value of a variable code will be like df.loc['3/1/2017',:]
# but now as the date column is the ondex we can directly use it

# To keep a copy of a data set

In [30]:
df1=df.copy()

# To resample a date time index data based on annual mean result

In [ ]:
# used to resample time series data
data2.resample("A").mean()
# here A means Annual and M means Monthly
# instead of .mean() we can use .first()- which will get the resample values to first day of the month
# or we can use .last() which will give resample values to last date of the month

# To interpolate the missing values if the first and last values of data are present then mid values can be interpolated

In [ ]:
data2.resample("M").first().interpolate("linear")
# nan values will be replaced by interpolated values 

# slice data frame

In [ ]:
data.loc[1:10,"HP":"Defense"]   # 10 and "Defense" are inclusive

# Reverse slice Data frame 

In [31]:
data.loc[10:1:-1,"HP":"Defense"] 

NameError: name 'data' is not defined

# To apply user defined function to the data series  

In [ ]:
def div(n):
    return n/2
data.HP.apply(div)
##### or like
data.HP.apply(lambda n : n/2)

# To change the name of index column  

In [ ]:
data.index.name = "index_name"
data.head()

# Hierarchical indexing  

In [ ]:
data1 = data.set_index(["Type 1","Type 2"]) 

# pivot table

In [ ]:
# pivoting
df.pivot(index="treatment",columns = "gender",values="response")

# how .copy() is different from normal assinging the df 

In [ ]:
df_copy=df.copy()
def fn():
    df.Visitors=(df.Visitors)*2
    return df.Visitors
def fn2():
    df_copy.Visitors=(df_copy.Visitors)*2
    return df_copy.Visitors
# if .copy() fn is used both fn() and fn2() will give same result but if df_copy=df is used then fn2() will give twice the value 
# of fn()

# you can unstack multiple index data frame 

In [ ]:
df1.unstack(level=0)

# To remove all index and set the default index

In [ ]:
df=df.reset_index()

# To swap levels of the index in multi index data frame

In [ ]:
df2 = df1.swaplevel(0,1)

# Code to apply multiple if else statement to pandas data frame 

In [ ]:
  
import pandas as pd 
pd.set_option('display.max_columns', 500)
df=pd.read_csv("https://media-doselect.s3.amazonaws.com/generic/OzvzVqK4pgg4x7qEadoZMRyVR/insurance.csv")
def bmi_group(val):
    if val<18.5:
        return "Underweight"
    if (val>=18.5) & (val<24.9):
        return "Normal"
    if (val>=24.9) & (val<=29.9):
        return "Overweight"
    if val>=30:
        return "Obese"
    
df["BMI_group"] = df.bmi.apply(bmi_group)
print(df.head())

# To get location of element in a series  

In [ ]:
  
import pandas as pd
d=[1,2]
n=[1,2,3,4,5]
e=pd.Series(d)
b=pd.Series(n)
a=[pd.Index(b).get_loc(i) for i in e]
print(a)
print(pd.Index(b).get_loc(3))

# To get the index of a data frame/columns 

In [ ]:
df.columns
df.index

# immutable classes in python are hashable like string / tuple / integers etc 

# IF groupby statement is changed to a data frame grouped by column becomes the index of the data frame 

In [ ]:
df_Fun=df.groupby('furnishingstatus')['area'].mean().sort_values(ascending=False)
df_Fun=pd.DataFrame(df_Fun)
df_Fun.head()

# To create n no b/w two limits with equal gap 

In [5]:
import numpy as np
x1 = np.linspace(0, 10, 20)
x1

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

# n nos b\w a limit with a difference 

In [4]:
x3 = np.arange(0.0, 1, 0.01) 
x3

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99])

# Randoms 

In [32]:
# all positive and negative values
np.random.randn(10)

array([ 0.77553394, -0.22976489,  0.12572275, -0.58910509,  1.23447832,
       -0.01311852, -1.31404965, -0.44568153, -2.17976111,  0.7583765 ])

In [33]:
# only positive or absolute value
np.random.rand(10)

array([0.61247533, 0.37204272, 0.78034134, 0.69161735, 0.79858096,
       0.97019792, 0.75688242, 0.74322382, 0.3740365 , 0.19864834])

In [34]:
np.random.randint(10)

8

# To get unique elements in a column 

In [ ]:
percentage_people_below_poverty_level['Geographic Area'].unique()

# To get random data from data set 

In [ ]:
#random data 
data.sample(5) # u can also use argument frac=0.1 to get 10% values from data set randomly 

# why %matplotlib inline not working  

In [1]:
import matplotlib.pyplot as plt
print(plt.get_backend())
# as the back end is already in inline 
# basically all the plots can be produced without any plt.show() or %matplotlib inline

module://ipykernel.pylab.backend_inline


# Using query command import rows with filters

In [ ]:
import pandas as pd

# Data frame from csv file
data = pd.read_csv("D:\\heart.csv")

data.query('chol < 230', inplace=True)

# Result
print(data)

# To form a series of date / date range

In [3]:
import pandas as pd
pd.date_range(start='2018-04-24', end='2018-04-27', periods=3)

DatetimeIndex(['2018-04-24 00:00:00', '2018-04-25 12:00:00',
               '2018-04-27 00:00:00'],
              dtype='datetime64[ns]', freq=None)

# To round off decimal to nearest integer 

In [2]:
import numpy as np

a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
np.rint(a)

array([-2., -2., -0.,  0.,  2.,  2.,  2.])

# use multiple if else for changing elements of a row 

In [ ]:
import pandas as pd 
pd.set_option('display.max_columns', 500)
df=pd.read_csv("https://media-doselect.s3.amazonaws.com/generic/OzvzVqK4pgg4x7qEadoZMRyVR/insurance.csv")
def bmi_group(val):
    if val<18.5:
        return "Underweight"
    if (val>=18.5) & (val<24.9):
        return "Normal"
    if (val>=24.9) & (val<=29.9):
        return "Overweight"
    if val>=30:
        return "Obese"

df["BMI_group"] = df.bmi.apply(bmi_group)
print(df.head())